name: delivery
description: Delivery project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infrastructure:
    path: "lib/infrastructure"
  domain:
    path: "lib/domain"

  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  dartz: ^0.10.1
  rxdart: ^0.27.4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
  assets:
    - assets/empty_placeholder.png
